import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { NavBar } from "@/components/basic/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className={cn(
                    inter.className,
                    'min-h-screen bg-background font-sans antialiased'
                )}>
                <NavBar />
                <main className="flex-1">
                    {children}
                </main>
                <Toaster />
            </body>
        </html>
    );
}
